language: objective-c
osx_image: xcode8.3
xcode_project: Mqtt.xcodeproj
# xcode_workspace: <WORKSPACE_PLACEHOLDER>
xcode_scheme: Mqtt
# xcode_sdk: iphonesimulator9.3
# env:
#   global: 
#     - FRAMEWORK_NAME=<THIS_IS_A_PLACEHOLDER_REPLACE_ME>
# before_install:
#   - brew update
#   - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  # - carthage bootstrap  
  # request swift package manager depdencies
  - swift package fetch
# before_deploy:
#   - carthage build --no-skip-current
#   - carthage archive $FRAMEWORK_NAME